// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace YourNamespace
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class Address : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""Address"",""namespace"":""YourNamespace"",""fields"":[{""name"":""Street"",""doc"":""Street address of the user."",""type"":""string""},{""name"":""City"",""doc"":""City where the user resides."",""type"":""string""},{""name"":""State"",""doc"":""State where the user resides."",""type"":""string""},{""name"":""Country"",""doc"":""Country of residence."",""type"":""string""},{""name"":""PostalCode"",""doc"":""Postal code of the user's address."",""type"":""string""}]}");
		/// <summary>
		/// Street address of the user.
		/// </summary>
		private string _Street;
		/// <summary>
		/// City where the user resides.
		/// </summary>
		private string _City;
		/// <summary>
		/// State where the user resides.
		/// </summary>
		private string _State;
		/// <summary>
		/// Country of residence.
		/// </summary>
		private string _Country;
		/// <summary>
		/// Postal code of the user's address.
		/// </summary>
		private string _PostalCode;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Address._SCHEMA;
			}
		}
		/// <summary>
		/// Street address of the user.
		/// </summary>
		public string Street
		{
			get
			{
				return this._Street;
			}
			set
			{
				this._Street = value;
			}
		}
		/// <summary>
		/// City where the user resides.
		/// </summary>
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				this._City = value;
			}
		}
		/// <summary>
		/// State where the user resides.
		/// </summary>
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				this._State = value;
			}
		}
		/// <summary>
		/// Country of residence.
		/// </summary>
		public string Country
		{
			get
			{
				return this._Country;
			}
			set
			{
				this._Country = value;
			}
		}
		/// <summary>
		/// Postal code of the user's address.
		/// </summary>
		public string PostalCode
		{
			get
			{
				return this._PostalCode;
			}
			set
			{
				this._PostalCode = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Street;
			case 1: return this.City;
			case 2: return this.State;
			case 3: return this.Country;
			case 4: return this.PostalCode;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Street = (System.String)fieldValue; break;
			case 1: this.City = (System.String)fieldValue; break;
			case 2: this.State = (System.String)fieldValue; break;
			case 3: this.Country = (System.String)fieldValue; break;
			case 4: this.PostalCode = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
