// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace YourNamespace
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class guid : SpecificFixed
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"fixed\",\"name\":\"guid\",\"namespace\":\"YourNamespace\",\"size\":16}");
		private static uint fixedSize = 16;
		public guid() : 
				base(fixedSize)
		{
		}
		public override global::Avro.Schema Schema
		{
			get
			{
				return guid._SCHEMA;
			}
		}
		public static uint FixedSize
		{
			get
			{
				return guid.fixedSize;
			}
		}
	}
}
